name: Build React App from ZIP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install unzip
        run: sudo apt-get install unzip -y

      - name: Extract ZIP
        run: unzip smart-income-manager-1 (1).zip -d extracted

      - name: Install Dependencies
        run: |
          cd extracted
          npm install

      - name: Build Project
        run: |
          cd extracted
          npm run build

      - name: Upload build folder
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: extracted/build
